<h2>BTC Price Data Connection</h2>

How can we get hold of BTC price data, both live **and** historical.

In [1]:
import numpy as np
import pandas as pd

<h3>yfinance

Only really need the basic daily historical data, and the 'live' price.

In [2]:
import yfinance as yf

In [3]:
btc_data = yf.download('BTC-USD', period='1y', interval='1d')
print(type(btc_data))
btc_data.head()

[*********************100%***********************]  1 of 1 completed

<class 'pandas.DataFrame'>

Price,Close,High,Low,Open,Volume
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD
Date,,,,,
2025-09-30,114056.085938,114836.617188,112740.562500,114396.523438,58986330258
2025-10-01,118648.929688,118648.929688,113981.398438,114057.593750,71328680132
2025-10-02,120681.257812,121086.406250,118383.156250,118652.382812,71415163912
2025-10-03,122266.531250,123944.703125,119344.312500,120656.984375,83941392228
2025-10-04,122425.429688,122857.640625,121577.570312,122267.468750,36769171735

In [4]:
btc_data.tail(5)

Price,Close,High,Low,Open,Volume
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD
Date,,,,,
2026-09-26,84406.453125,84423.179688,83781.109375,84035.820312,15169336375
2026-09-27,84458.085938,85126.109375,84121.328125,84412.718750,19386591468
2026-09-28,83502.609375,84972.664062,82570.718750,84454.117188,42589028679
2026-09-29,83622.429688,84511.281250,82739.093750,83500.320312,28029782264
2026-09-30,84224.007812,85581.343750,82956.867188,83624.789062,36088528896

Restructure the multi-index dataframe into a single index dataframe:

In [6]:
btc_data.columns = btc_data.columns.get_level_values(0)
btc_data = btc_data.reset_index()
btc_data.head()

Price,Date,Close,High,Low,Open,Volume
0,2025-09-30,114056.085938,114836.617188,112740.562500,114396.523438,58986330258
1,2025-10-01,118648.929688,118648.929688,113981.398438,114057.593750,71328680132
2,2025-10-02,120681.257812,121086.406250,118383.156250,118652.382812,71415163912
3,2025-10-03,122266.531250,123944.703125,119344.312500,120656.984375,83941392228
4,2025-10-04,122425.429688,122857.640625,121577.570312,122267.468750,36769171735