<h2>Modelling: Future Price Direction 4 (LSTM)

<h3>Data Preparation

In [96]:
# Load pre split data:
from project_paths import RAW_DATA_PATH
import pandas as pd

from bta_direction_functions import add_direction
print(RAW_DATA_PATH)

raw_data = pd.read_pickle(RAW_DATA_PATH)
nd_data = raw_data.copy()
nd_data.head()

C:\Users\cochr\Data Science Projects\vlXsnPPgKKnWqEJB\data\raw\btcusd_data.pkl

Price       Date       Close        High         Low        Open    Volume
0     2014-09-17  457.334015  468.174011  452.421997  465.864014  21056800
1     2014-09-18  424.440002  456.859985  413.104004  456.859985  34483200
2     2014-09-19  394.795990  427.834991  384.532013  424.102997  37919700
3     2014-09-20  408.903992  423.295990  389.882996  394.673004  36863600
4     2014-09-21  398.821014  412.425995  393.181000  408.084991  26580100

In [97]:
data_20 = add_direction(data=nd_data, shift=20, price="Close")
data_20 = data_20.drop(columns=["Date"])
data_20.head()

Price       Close        High         Low        Open    Volume  Direction_20
0      457.334015  468.174011  452.421997  465.864014  21056800             0
1      424.440002  456.859985  413.104004  456.859985  34483200             0
2      394.795990  427.834991  384.532013  424.102997  37919700             0
3      408.903992  423.295990  389.882996  394.673004  36863600             0
4      398.821014  412.425995  393.181000  408.084991  26580100             0

In [98]:
from bta_direction_functions import add_EMA, add_SMA

Let's add _5 (1 week), _10 (2 week_), _20 (1 month) SMAs and EMAs. Leave out MACD, RSI and ATR.

In [99]:
data_20 = add_SMA(data=data_20,n=5,price="Close")
data_20 = add_SMA(data=data_20,n=10,price="Close")
data_20 = add_SMA(data=data_20,n=20,price="Close")

data_20 = add_EMA(data=data_20,n=5,price="Close")
data_20 = add_EMA(data=data_20,n=10,price="Close")
data_20 = add_EMA(data=data_20,n=20,price="Close")

In [100]:
data_20 = data_20.dropna().copy() # Drop NA rows
data_20.head()

Price,Close,High,Low,Open,Volume,Direction_20,SMA_5,SMA_10,SMA_20,EMA_5,EMA_10,EMA_20
19,330.079010,345.134003,302.559998,320.389008,79011800,1,342.807800,363.676599,389.910399,341.195946,359.626329,383.883180
20,336.187012,339.247009,320.481995,330.584015,49199900,1,335.030804,357.343301,383.853049,339.526301,355.364635,379.340688
21,352.940002,354.364014,327.187988,336.115997,54736300,1,333.716406,354.919202,380.278049,343.997535,354.923793,376.826337
22,365.026001,382.726013,347.687012,352.747986,83641104,0,340.948407,353.875101,378.789549,351.007024,356.760558,375.702495
23,361.562012,375.066986,352.963013,364.687012,43665700,0,349.158807,351.336902,376.422450,354.525353,357.633549,374.355783

- Remove Volume, Open, SMA_5, and Low in the modelling pipeline based on the feature selection from the previous notebook.
- Temporal train-test split.
- Scale numerical features on training split
- Add overlap sequences
- Train an LSTM.

In [101]:
X = data_20.drop(columns=["Direction_20"])
y = data_20["Direction_20"]

In [102]:
split_idx = int(len(X) * 0.8)
val_idx = int(split_idx * 0.8)

X_train, X_val, X_test = X.iloc[:val_idx], X.iloc[val_idx:split_idx], X.iloc[split_idx:]
y_train, y_val, y_test = y.iloc[:val_idx], y.iloc[val_idx:split_idx], y.iloc[split_idx:]

print(f"Training samples: {len(X_train)} | Validation samples: {len(X_val)} | Test samples: {len(X_test)}")

Training samples: 2789 | Validation samples: 698 | Test samples: 872

<h4>Data Preprocessing Pipeline:

In [103]:
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin

In [104]:
# Function to generate lag features in a pipeline:
import numpy as np
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.utils.validation import check_is_fitted

class RollingWindowTransformer(BaseEstimator, TransformerMixin):
    def __init__(self, lookback=96):
        self.lookback = lookback

    def fit(self, X, y=None):
        X = np.asarray(X)
        self.n_features_in_ = X.shape[1]
        return self

    def transform(self, X):
        check_is_fitted(self)

        X = np.asarray(X, dtype=np.float32)

        if X.ndim != 2:
            raise ValueError("X must be 2D")

        if X.shape[1] != self.n_features_in_:
            raise ValueError("Number of features has changed")

        if not 1 <= self.lookback <= len(X):
            raise ValueError("Invalid lookback")

        return np.stack([
            X[i:i + self.lookback]
            for i in range(len(X) - self.lookback + 1)
        ])

In [105]:
lookback = 48

In [106]:
# Processing pipeleine only not a modelling pipeline:
process_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("rolling", RollingWindowTransformer(lookback=lookback))
])

In [107]:
X_train_seq = process_pipeline.fit_transform(X_train)
X_val_seq = process_pipeline.transform(X_val)
X_test_seq = process_pipeline.transform(X_test)

print(X_train_seq.shape)
print(X_val_seq.shape)
print(X_test_seq.shape)

(2742, 48, 11)
(651, 48, 11)
(825, 48, 11)

In [108]:
# The rolling transformation reduces the number of samples by lookback - 1. Consequently, the target must be aligned with the end of each sequence:

y_train_seq = np.asarray(y_train)[lookback - 1:]
y_val_seq = np.asarray(y_val)[lookback - 1:]
y_test_seq = np.asarray(y_test)[lookback - 1:]

print(y_train_seq.shape)
print(y_val_seq.shape)
print(y_test_seq.shape)

(2742,)
(651,)
(825,)

In [109]:
# Check that the pipeline is fitted. If this runs without an error, the pipeline is recognised as fitted:
check_is_fitted(process_pipeline)

print(process_pipeline.named_steps["rolling"].n_features_in_)

11

<h3>LSTM Model Training

In [110]:
import tensorflow as tf
from tensorflow.keras import Sequential, Input
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.regularizers import l2
from tensorflow.keras.optimizers import Adam

<h4>Model Definition:

In [111]:
tf.keras.utils.set_random_seed(13)

model_1 = Sequential([
    Input(shape=(X_train_seq.shape[1], X_train_seq.shape[2])),

    LSTM(
        units=32,
        return_sequences=False
    ),

    Dropout(0.2),

    Dense(
        units=16,
        activation="relu",
        kernel_regularizer=l2(1e-4)
    ),

    Dense(
        units=1,
        activation="sigmoid"
    )
])

In [112]:
model_1.compile(
    optimizer=Adam(learning_rate=1e-3),
    loss="binary_crossentropy",
    metrics=[
        tf.keras.metrics.BinaryAccuracy(name="accuracy"),
        tf.keras.metrics.AUC(name="roc_auc")
    ]
)

model_1.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_14 (LSTM)                  │ (None, 32)             │         5,632 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_17 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_19 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_20 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 6,177 (24.13 KB)

 Trainable params: 6,177 (24.13 KB)

 Non-trainable params: 0 (0.00 B)

<h4>Model Training:

In [113]:
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

In [114]:
callbacks = [
    EarlyStopping(
        monitor="val_loss",
        patience=20,
        min_delta=1e-4,
        restore_best_weights=True
    ),

    ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=20,
        min_lr=1e-5
    )
]

history_1 = model_1.fit(
    X_train_seq,
    y_train_seq,
    validation_data=(X_val_seq, y_val_seq),
    epochs=1000,
    batch_size=64,
    shuffle=False,
    callbacks=callbacks, 
    verbose=1
)

Epoch 1/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 14ms/step - accuracy: 0.5532 - loss: 0.6908 - roc_auc: 0.5310 - val_accuracy: 0.4823 - val_loss: 0.6969 - val_roc_auc: 0.5427 - learning_rate: 0.0010
Epoch 2/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5718 - loss: 0.6836 - roc_auc: 0.5647 - val_accuracy: 0.5100 - val_loss: 0.6934 - val_roc_auc: 0.5554 - learning_rate: 0.0010
Epoch 3/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5904 - loss: 0.6732 - roc_auc: 0.5855 - val_accuracy: 0.5023 - val_loss: 0.6950 - val_roc_auc: 0.5148 - learning_rate: 0.0010
Epoch 4/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5945 - loss: 0.6728 - roc_auc: 0.5875 - val_accuracy: 0.5023 - val_loss: 0.6977 - val_roc_auc: 0.5107 - learning_rate: 0.0010
Epoch 5/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5897 - loss: 0.6757 - roc_auc: 0.5822 - val_accuracy: 0.5300 - val_loss: 0.6938 - val_roc_auc: 0.4921 - learning_rate: 0.0010
Epoch 6/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5999 - loss: 0.6682 - roc_auc: 0.5976 - val_accuracy: 0.5023 - val_loss: 0.7034 - val_roc_auc: 0.4978 - learning_rate: 0.0010
Epoch 7/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6018 - loss: 0.6651 - roc_auc: 0.6138 - val_accuracy: 0.5054 - val_loss: 0.7234 - val_roc_auc: 0.4756 - learning_rate: 0.0010
Epoch 8/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6014 - loss: 0.6639 - roc_auc: 0.6154 - val_accuracy: 0.5484 - val_loss: 0.7072 - val_roc_auc: 0.4874 - learning_rate: 0.0010
Epoch 9/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6076 - loss: 0.6633 - roc_auc: 0.6064 - val_accuracy: 0.5499 - val_loss: 0.7038 - val_roc_auc: 0.4852 - learning_rate: 0.0010
Epoch 10/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6080 - loss: 0.6607 - roc_auc: 0.6219 - val_accuracy: 0.5361 - val_loss: 0.7136 - val_roc_auc: 0.4626 - learning_rate: 0.0010
Epoch 11/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6127 - loss: 0.6558 - roc_auc: 0.6341 - val_accuracy: 0.5023 - val_loss: 0.7376 - val_roc_auc: 0.4786 - learning_rate: 0.0010
Epoch 12/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6101 - loss: 0.6523 - roc_auc: 0.6367 - val_accuracy: 0.5315 - val_loss: 0.7454 - val_roc_auc: 0.4513 - learning_rate: 0.0010
Epoch 13/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6295 - loss: 0.6560 - roc_auc: 0.6256 - val_accuracy: 0.5131 - val_loss: 0.7283 - val_roc_auc: 0.4546 - learning_rate: 0.0010
Epoch 14/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6368 - loss: 0.6510 - roc_auc: 0.6374 - val_accuracy: 0.5161 - val_loss: 0.7373 - val_roc_auc: 0.4419 - learning_rate: 0.0010
Epoch 15/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6320 - loss: 0.6477 - roc_auc: 0.6454 - val_accuracy: 0.5392 - val_loss: 0.7721 - val_roc_auc: 0.4364 - learning_rate: 0.0010
Epoch 16/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6506 - loss: 0.6447 - roc_auc: 0.6460 - val_accuracy: 0.4363 - val_loss: 0.7754 - val_roc_auc: 0.4297 - learning_rate: 0.0010
Epoch 17/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6419 - loss: 0.6421 - roc_auc: 0.6521 - val_accuracy: 0.5499 - val_loss: 0.8521 - val_roc_auc: 0.4551 - learning_rate: 0.0010
Epoch 18/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6127 - loss: 0.7000 - roc_auc: 0.5434 - val_accuracy: 0.5760 - val_loss: 0.7142 - val_roc_auc: 0.5045 - learning_rate: 0.0010
Epoch 19/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.5945 - loss: 0.6787 - roc_auc: 0.5747 - val_accuracy: 0.5376 - val_loss: 0.7002 - val_roc_auc: 0.5268 - learning_rate: 0.0010
Epoch 20/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6127 - loss: 0.6663 - roc_auc: 0.6018 - val_accuracy: 0.5576 - val_loss: 0.6900 - val_roc_auc: 0.5118 - learning_rate: 0.0010
Epoch 21/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6189 - loss: 0.6603 - roc_auc: 0.6135 - val_accuracy: 0.5730 - val_loss: 0.6913 - val_roc_auc: 0.5056 - learning_rate: 0.0010
Epoch 22/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6171 - loss: 0.6554 - roc_auc: 0.6274 - val_accuracy: 0.5453 - val_loss: 0.6973 - val_roc_auc: 0.5069 - learning_rate: 0.0010
Epoch 23/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6306 - loss: 0.6477 - roc_auc: 0.6418 - val_accuracy: 0.5653 - val_loss: 0.7031 - val_roc_auc: 0.5063 - learning_rate: 0.0010
Epoch 24/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6291 - loss: 0.6482 - roc_auc: 0.6396 - val_accuracy: 0.5438 - val_loss: 0.7172 - val_roc_auc: 0.5107 - learning_rate: 0.0010
Epoch 25/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6207 - loss: 0.6531 - roc_auc: 0.6404 - val_accuracy: 0.4931 - val_loss: 0.7322 - val_roc_auc: 0.5149 - learning_rate: 0.0010
Epoch 26/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6393 - loss: 0.6418 - roc_auc: 0.6499 - val_accuracy: 0.5545 - val_loss: 0.7365 - val_roc_auc: 0.5077 - learning_rate: 0.0010
Epoch 27/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6419 - loss: 0.6413 - roc_auc: 0.6463 - val_accuracy: 0.5453 - val_loss: 0.7525 - val_roc_auc: 0.5055 - learning_rate: 0.0010
Epoch 28/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6342 - loss: 0.6375 - roc_auc: 0.6605 - val_accuracy: 0.5392 - val_loss: 0.7700 - val_roc_auc: 0.5052 - learning_rate: 0.0010
Epoch 29/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6379 - loss: 0.6398 - roc_auc: 0.6483 - val_accuracy: 0.5407 - val_loss: 0.7845 - val_roc_auc: 0.5078 - learning_rate: 0.0010
Epoch 30/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6484 - loss: 0.6433 - roc_auc: 0.6378 - val_accuracy: 0.5346 - val_loss: 0.8193 - val_roc_auc: 0.5080 - learning_rate: 0.0010
Epoch 31/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6437 - loss: 0.6363 - roc_auc: 0.6572 - val_accuracy: 0.5392 - val_loss: 0.7638 - val_roc_auc: 0.5091 - learning_rate: 0.0010
Epoch 32/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6524 - loss: 0.6323 - roc_auc: 0.6611 - val_accuracy: 0.5407 - val_loss: 0.7933 - val_roc_auc: 0.5030 - learning_rate: 0.0010
Epoch 33/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6524 - loss: 0.6284 - roc_auc: 0.6720 - val_accuracy: 0.5392 - val_loss: 0.8116 - val_roc_auc: 0.5033 - learning_rate: 0.0010
Epoch 34/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6408 - loss: 0.6333 - roc_auc: 0.6671 - val_accuracy: 0.5131 - val_loss: 0.8207 - val_roc_auc: 0.4860 - learning_rate: 0.0010
Epoch 35/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6692 - loss: 0.6126 - roc_auc: 0.7019 - val_accuracy: 0.5407 - val_loss: 0.8358 - val_roc_auc: 0.5041 - learning_rate: 0.0010
Epoch 36/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6787 - loss: 0.6081 - roc_auc: 0.7074 - val_accuracy: 0.5407 - val_loss: 0.8517 - val_roc_auc: 0.4940 - learning_rate: 0.0010
Epoch 37/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6674 - loss: 0.6170 - roc_auc: 0.6924 - val_accuracy: 0.5100 - val_loss: 0.8473 - val_roc_auc: 0.4814 - learning_rate: 0.0010
Epoch 38/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6707 - loss: 0.6117 - roc_auc: 0.6930 - val_accuracy: 0.5376 - val_loss: 0.8551 - val_roc_auc: 0.4874 - learning_rate: 0.0010
Epoch 39/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6583 - loss: 0.6241 - roc_auc: 0.6701 - val_accuracy: 0.5422 - val_loss: 0.8723 - val_roc_auc: 0.4840 - learning_rate: 0.0010
Epoch 40/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6488 - loss: 0.6263 - roc_auc: 0.6812 - val_accuracy: 0.5361 - val_loss: 0.8989 - val_roc_auc: 0.5018 - learning_rate: 0.0010

In [115]:
best_epoch_idx = int(np.argmin(history_1.history["val_loss"])) # Define best epoch as the one with the lowest validation loss.

print(f"Best epoch: {best_epoch_idx + 1}")
for metric, values in history_1.history.items():
    print(f"{metric}: {values[best_epoch_idx]:.4f}")

Best epoch: 20
accuracy: 0.6127
loss: 0.6663
roc_auc: 0.6018
val_accuracy: 0.5576
val_loss: 0.6900
val_roc_auc: 0.5118
learning_rate: 0.0010

That was a fairly simple model that may not have been able to pick up any complex temporal relationships that may be present becuase it is only a single layer model. We have however established a baseline model (and modelling layout) making subsquent experimentation easier.

In [116]:
model_2 = Sequential([
    Input(shape=(X_train_seq.shape[1], X_train_seq.shape[2])),

    # First LSTM layer
    LSTM(
        units=128,
        return_sequences=True
    ),
    Dropout(0.5),

    # Second LSTM layer
    LSTM(
        units=64,
        return_sequences=True
    ),
    Dropout(0.5),

    # Third LSTM layer
    LSTM(
        units=32,
        return_sequences=False
    ),
    Dropout(0.5),

    # Fully connected layers
    Dense(
        units=32,
        activation="relu",
        kernel_regularizer=l2(1e-4)
    ),
    Dropout(0.5),

    Dense(
        units=16,
        activation="relu",
        kernel_regularizer=l2(1e-4)
    ),

    # Binary classification output
    Dense(
        units=1,
        activation="sigmoid"
    )
])

model_2.compile(
    optimizer=Adam(learning_rate=3e-4),
    loss="binary_crossentropy",
    metrics=[
        tf.keras.metrics.BinaryAccuracy(name="accuracy"),
        tf.keras.metrics.AUC(name="roc_auc")
    ]
)

model_2.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_15 (LSTM)                  │ (None, 48, 128)        │        71,680 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_18 (Dropout)            │ (None, 48, 128)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_16 (LSTM)                  │ (None, 48, 64)         │        49,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_19 (Dropout)            │ (None, 48, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_17 (LSTM)                  │ (None, 32)             │        12,416 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_20 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_21 (Dense)                │ (None, 32)             │         1,056 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_21 (Dropout)            │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_22 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_23 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 135,105 (527.75 KB)

 Trainable params: 135,105 (527.75 KB)

 Non-trainable params: 0 (0.00 B)

In [117]:
callbacks = [
    EarlyStopping(
        monitor="val_loss",
        patience=20,
        min_delta=1e-4,
        restore_best_weights=True
    ),

    ReduceLROnPlateau(
        monitor="val_loss",
        factor=0.5,
        patience=20,
        min_lr=1e-6
    )
]

history_2 = model_2.fit(
    X_train_seq,
    y_train_seq,
    validation_data=(X_val_seq, y_val_seq),
    epochs=1000,
    batch_size=64,
    shuffle=False,
    callbacks=callbacks, 
    verbose=1
)

Epoch 1/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 4s 45ms/step - accuracy: 0.5605 - loss: 0.6954 - roc_auc: 0.4967 - val_accuracy: 0.5392 - val_loss: 0.6982 - val_roc_auc: 0.4536 - learning_rate: 3.0000e-04
Epoch 2/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - accuracy: 0.5755 - loss: 0.6869 - roc_auc: 0.5485 - val_accuracy: 0.4793 - val_loss: 0.7012 - val_roc_auc: 0.4856 - learning_rate: 3.0000e-04
Epoch 3/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - accuracy: 0.5821 - loss: 0.6838 - roc_auc: 0.5628 - val_accuracy: 0.4854 - val_loss: 0.6993 - val_roc_auc: 0.4801 - learning_rate: 3.0000e-04
Epoch 4/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - accuracy: 0.5813 - loss: 0.6859 - roc_auc: 0.5571 - val_accuracy: 0.4885 - val_loss: 0.7031 - val_roc_auc: 0.4729 - learning_rate: 3.0000e-04
Epoch 5/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - accuracy: 0.5828 - loss: 0.6836 - roc_auc: 0.5714 - val_accuracy: 0.4747 - val_loss: 0.7064 - val_roc_auc: 0.4578 - learning_rate: 3.0000e-04
Epoch 6/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - accuracy: 0.5923 - loss: 0.6780 - roc_auc: 0.5897 - val_accuracy: 0.4624 - val_loss: 0.7147 - val_roc_auc: 0.4718 - learning_rate: 3.0000e-04
Epoch 7/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - accuracy: 0.5894 - loss: 0.6764 - roc_auc: 0.5898 - val_accuracy: 0.4700 - val_loss: 0.7261 - val_roc_auc: 0.4597 - learning_rate: 3.0000e-04
Epoch 8/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - accuracy: 0.5883 - loss: 0.6821 - roc_auc: 0.5807 - val_accuracy: 0.4178 - val_loss: 0.7237 - val_roc_auc: 0.4679 - learning_rate: 3.0000e-04
Epoch 9/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - accuracy: 0.5879 - loss: 0.6807 - roc_auc: 0.5853 - val_accuracy: 0.4286 - val_loss: 0.7201 - val_roc_auc: 0.4747 - learning_rate: 3.0000e-04
Epoch 10/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - accuracy: 0.5963 - loss: 0.6781 - roc_auc: 0.5925 - val_accuracy: 0.4224 - val_loss: 0.7209 - val_roc_auc: 0.5145 - learning_rate: 3.0000e-04
Epoch 11/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - accuracy: 0.5945 - loss: 0.6796 - roc_auc: 0.5918 - val_accuracy: 0.4224 - val_loss: 0.7264 - val_roc_auc: 0.4903 - learning_rate: 3.0000e-04
Epoch 12/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - accuracy: 0.6021 - loss: 0.6720 - roc_auc: 0.6080 - val_accuracy: 0.4777 - val_loss: 0.7287 - val_roc_auc: 0.4437 - learning_rate: 3.0000e-04
Epoch 13/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - accuracy: 0.5992 - loss: 0.6729 - roc_auc: 0.6018 - val_accuracy: 0.4747 - val_loss: 0.7434 - val_roc_auc: 0.4870 - learning_rate: 3.0000e-04
Epoch 14/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - accuracy: 0.6116 - loss: 0.6647 - roc_auc: 0.6283 - val_accuracy: 0.4531 - val_loss: 0.7608 - val_roc_auc: 0.4605 - learning_rate: 3.0000e-04
Epoch 15/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - accuracy: 0.6171 - loss: 0.6658 - roc_auc: 0.6328 - val_accuracy: 0.3932 - val_loss: 0.7861 - val_roc_auc: 0.4457 - learning_rate: 3.0000e-04
Epoch 16/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 1s 35ms/step - accuracy: 0.6087 - loss: 0.6659 - roc_auc: 0.6265 - val_accuracy: 0.3871 - val_loss: 0.7934 - val_roc_auc: 0.4903 - learning_rate: 3.0000e-04
Epoch 17/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - accuracy: 0.6233 - loss: 0.6654 - roc_auc: 0.6247 - val_accuracy: 0.4485 - val_loss: 0.8155 - val_roc_auc: 0.4635 - learning_rate: 3.0000e-04
Epoch 18/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - accuracy: 0.6072 - loss: 0.6738 - roc_auc: 0.6113 - val_accuracy: 0.4316 - val_loss: 0.7531 - val_roc_auc: 0.4652 - learning_rate: 3.0000e-04
Epoch 19/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 38ms/step - accuracy: 0.6018 - loss: 0.6808 - roc_auc: 0.5839 - val_accuracy: 0.4178 - val_loss: 0.7493 - val_roc_auc: 0.4646 - learning_rate: 3.0000e-04
Epoch 20/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - accuracy: 0.6116 - loss: 0.6715 - roc_auc: 0.6094 - val_accuracy: 0.4270 - val_loss: 0.7461 - val_roc_auc: 0.5041 - learning_rate: 3.0000e-04
Epoch 21/1000
43/43 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - accuracy: 0.6123 - loss: 0.6682 - roc_auc: 0.6143 - val_accuracy: 0.4301 - val_loss: 0.7474 - val_roc_auc: 0.4714 - learning_rate: 3.0000e-04

The problem with higher parameter models on relatively small training datasets like we have here is the risk of overfitting.

Are we going about this properly? Are we naive to just assume that the lookback periods we have been selecting are good enough.

Read the following article: https://medium.com/data-science-collective/future-forecasting-of-time-series-using-lstm-a-quick-guide-for-business-leaders-370661c574c9

In this article the author uses partial auto correlation function (PACF) which measures how much the y variable is correlated to past values of itself and how far back a statistically significant correlation exists. The scalecast library is also used. scalecast is an ML library for time-series modelling that simplifies the whole process. May be worth trying?